Revert "a"
This reverts commit 2962c86f7cea5a4b71d0661669c606f77c0985c9.

diff --git a/cll_build b/cll_build
--- a/cll_build
+++ b/cll_build
@@ -163,6 +163,35 @@ then
   archivedir=""
 fi
 
+#**********
+# Get the correct xsl version, which we'll need pretty much no
+# matter what.
+#**********
+if [ -f xml/docbook-xsl-1.78.1.zip \
+  -a "$(md5sum xml/docbook-xsl-1.78.1.zip 2>&1)" = '51ed42fe67ed513763c5bd9f1abd680b  xml/docbook-xsl-1.78.1.zip' ]
+then
+  echo "xsl already downloaded; if you think this is in error, delete xml/docbook-xsl-1.78.1.zip"
+else
+  rm -rf xml/docbook-xsl-1.78.1*
+  # it would be best not to go to a specific mirror like this, but
+  # it's not obivous how to fix that
+  wget https://astuteinternet.dl.sourceforge.net/project/docbook/docbook-xsl/1.78.1/docbook-xsl-1.78.1.zip -O xml/docbook-xsl-1.78.1.zip
+fi
+
+if [ -d xml/docbook-xsl-1.78.1 -a "$(find xml/docbook-xsl-1.78.1 | sort | wc -l 2>&1)" = '1945' ]
+then
+  echo "xsl already unpacked; if you think this is in error, delete xml/docbook-xsl-1.78.1/ and/or xml/docbook-xsl-1.78.1.zip"
+else
+  rm -rf xml/docbook-xsl-1.78.1/
+  bash -c "cd xml/ ; unzip docbook-xsl-1.78.1.zip"
+fi
+
+if [ "$(find xml/docbook-xsl-1.78.1 | sort | wc -l 2>&1)" != '1945' ]
+then
+  echo -e "\n\nI don't see valid unpacked xsl in xml/docbook-xsl-1.78.1; bailing.\n\n"
+  exit 1
+fi
+
 echo "chapters: $chapters"
 echo "optlist: $optlist"
 echo "target: $target"
